### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by anderius** [jayway/terraform-provider-mssql#2]
Thank you for this, @tomasaschan!

Do you plan to complete and publish this provider? If not, would it be OK to fork it, and attempt to do that? Or would you prefer pull requests back here (given you have time to publish, setup signing, review etc)?

**Comment by tomasaschan** [comment]
Nice that you like it! I haven't looked at this code since I wrote it in January 2019, and I don't even work at Jayway any longer. Since nobody else has picked up on this either, I assume there are no plans to do anything with this code. Consider it an abandoned experiment.

A former colleague helped me push a license file, though, so you should be all set to fork and build something awesome from this if you wish!

**Comment by anderius** [comment]
Thank you!

Time will show if something production ready will appear at: https://github.com/dsb-norge/terraform-provider-mssql/

And thanks to you too, @5imonGustafsson!
